src/Valet/Commands/Migrate.cs
This allows the `GITHUB_ACCESS_TOKEN` and `GITHUB_INSTANCE_URL` parameters to be configured with environment variables
```bash
$ GITHUB_ACCESS_TOKEN=$TOKEN dotnet run --project src/Valet/Valet.csproj -- migrate ...
```
=> Make GitHub access_token instance_url optional for `migrate` command

src/Valet/Commands/Forecast.cs, src/Valet/Commands/GitLab/Forecast.cs
This adds a jenkins subcommand for the forecast command.
```bash
dotnet run --project src/Valet/Valet.csproj -- forecast gitlab --namespace gitlab-org/quality -o tmp
```
=> Add gitlab subcommand for forecast

README.md, src/Valet/Commands/Circle/Audit.cs, src/Valet/Commands/Circle/Common.cs
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
Fix typos for CircleCI instead of Circle CI.
`git grep -q "Circle CI"; echo $?` should return non-0 status code:
```
$ git grep -q "Circle CI"; echo $?
1
```
=> Fix typos for CircleCI

README.md
Adds lines that mention support for Jenkins and GitLab for the `forecast` command in the README
👀
=> Add Jenkins + GitLab to `forecast` docs

src/Valet/Services/ProcessService.cs
Existing the ReadStream method early is somehow causing issues with the task cancellation.  Relocating the if(output) check to the inside of the while loop to allow all normal logic (including cancellation token) to run while still disabling output.
On a windows machine
```bash
$ dotnet run --project src/Valet/Valet.csproj -- version
```
Closes github/valet#4212
=> [Bugfix] Docker commands hang on output

README.md, src/Valet/Commands/Circle/Forecast.cs, src/Valet/Commands/Forecast.cs
Adds the forecast subcommand for CircleCI
Run 👇  as soon as [this](https://github.com/github/valet/pull/4216) is merged
`dotnet run --project src/Valet/Valet.csproj -- forecast circle-ci --circle-ci-organization $CIRCLE_CI_ORGANIZATION -o tmp`
Closes github/valet#4217
=> Add CircleCI forecast subcommand

README.md, src/Valet/Commands/Forecast.cs, src/Valet/Commands/Travis/Forecast.cs
Adds the forecast subcommand for Travis CI
Run 👇  as soon as [this](https://github.com/github/valet/pull/4241) is merged
```bash
dotnet run --project src/Valet/Valet.csproj -- forecast travis-ci --travis-ci-organization $TRAVIS_CI_ORGANIZATION -o tmp
```
Closes https://github.com/github/valet/issues/4239
=> Add Travis CI forecast subcommand

src/Valet/Commands/Circle/Common.cs
Fix typo for `source` instead of `srouce`.
`git grep -q "srouce"; echo $?` should return non-0 status code.
```console
❯ git grep -q "srouce"; echo $?
1
```
=> Fix typo for source instead of srouce

src/Valet.UnitTests/Services/DockerServiceTests.cs, src/Valet/App.cs, src/Valet/Commands/Update.cs, src/Valet/Interfaces/IDockerService.cs, src/Valet/Interfaces/IProcessService.cs, src/Valet/Services/DockerService.cs, src/Valet/Services/ProcessService.cs
This updates the `update` command to accept the PAT to auth with `ghcr.io` as standard input, to mirror the behavior of `docker login ...`. This has the benefit of keeping PATs away from terminal history.
Build the executable:
```bash
$ dotnet build src/Valet.sln
$ dotnet publish src/Valet/Valet.csproj -c Release -r osx-x64 --self-contained -o dist/osx-x64 --no-restore -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
```
then pipe input to the `update` command:
```bash
$ echo $GITHUB_PAT | dist/osx-x64/gh-valet update --username $GITHUB_USERNAME --password-stdin
```
Closes #40 
cc/ @korosuke613
=> Add `--password-stdin` option to securely provide creds

README.md, src/Valet.UnitTests/Models/VariableTests.cs, src/Valet.UnitTests/Services/ConfigurationServiceTests.cs, src/Valet/App.cs, src/Valet/Commands/Configure.cs, src/Valet/Constants.cs, src/Valet/Interfaces/IConfigurationService.cs, src/Valet/Models/Provider.cs, src/Valet/Models/Variable.cs, src/Valet/Program.cs, src/Valet/Services/ConfigurationService.cs, src/Valet/Services/DockerService.cs, src/Valet/Valet.csproj
This introduces a `configure` command to the CLI that is an interactive prompt to set a user's `.env.local` file. This command will only write new entries to the `.env.local` file if a value was provided in the interactive prompt. This is so that the command can be run multiple times and entries from previous runs will be preserved unless a new value was provided.
- Specs
```bash
$ dotnet run --project src/Valet/Valet.csproj -- configure
```
Closes github/valet#4090
=> Add command to configure environment variables

.github/ISSUE_TEMPLATE/support.yml, src/Valet/App.cs, src/Valet/Commands/Version.cs, src/Valet/Interfaces/IProcessService.cs, src/Valet/Program.cs, src/Valet/Services/ProcessService.cs
This creates a single `version` command that can be used to fetch the `gh` version, the `gh-valet` version, and the valet docker image all in one go. This will make the support request form simpler since now folks can send the output of a single command instead of 3. Further enhancements can be done to indicate if there are more recent versions of the valet-cli 
image available.
```bash
$ dotnet run --project src/Valet/Valet.csproj -- version
gh version 2.11.3 (2022-05-25)
gh valet        github/gh-valet v0.1.10
valet-cli       v0.1.0.12957
```
Closes #35
=> Update `version` command to output additional information

src/Valet.UnitTests/Models/StringExtensionsTests.cs, src/Valet/App.cs, src/Valet/Commands/Audit.cs, src/Valet/Commands/Common.cs, src/Valet/Commands/Forecast.cs, src/Valet/Commands/GitLab/Common.cs, src/Valet/Commands/Jenkins/Forecast.cs, src/Valet/Models/StringExtensions.cs
This ensures that arguments that contain a space have their spaces preserved when delegated to the valet-cli container. 
Additionally, this updates the `Option`s that are an array type to accept multiple input. This means that this is valid syntax once again `gh valet audit gitlab --namespace first second third -o output`
- Specs
```bash
$ dotnet run --project src/Valet/Valet.csproj -- audit azure-devops --azure-devops-project "name with spaces" -o output
```
Closes valet-customers/issue-ops#3
=> Escape arguments containing spaces

src/Valet/Commands/Audit.cs, src/Valet/Commands/Common.cs, src/Valet/Commands/DryRun.cs, src/Valet/Commands/Forecast.cs, src/Valet/Commands/Migrate.cs
Adds the --no-http-cache option to gh-valet and refactors the options to split options that are specific to transformer commands (`audit`, `dry-run`, `migrate`) from options that should be enabled for all commands including `forecast`
PS. Naming is hard 😆 
👀 
```
➜ dotnet run --project src/Valet/Valet.csproj -- forecast azure-devops --help
Options:
-g, --azure-devops-organization <azure-devops-organization>  The Azure DevOps organization name.
-p, --azure-devops-project <azure-devops-project>            The Azure DevOps project name.
-u, --azure-devops-instance-url <azure-devops-instance-url>  The URL of the Azure DevOps instance.
-t, --azure-devops-access-token <azure-devops-access-token>  Access token for the Azure DevOps instance.
-o, --output-dir <output-dir> (REQUIRED) …
```
=> Add --no-http-cache option and refactor options

src/Valet.UnitTests/AppTests.cs, src/Valet.UnitTests/Models/ManifestTests.cs, src/Valet.UnitTests/Services/DockerServiceTests.cs, src/Valet/App.cs, src/Valet/Interfaces/IDockerService.cs, src/Valet/Models/Docker/Manifest.cs, src/Valet/Models/Docker/ManifestConfig.cs, src/Valet/Program.cs, src/Valet/Services/DockerService.cs
Checking if the valet container image is up to date. If it is not up to date, then display a message to the user suggesting they run `gh valet update` to update their image.
Unit tests 🧪  You can also manually run it by forcing an older version of valet to be your latest version:
`docker pull ghcr.io/valet-customers/valet-cli:0.1.0.12602`
`docker image tag ghcr.io/valet-customers/valet-cli:0.1.0.12602 ghcr.io/valet-customers/valet-cli:latest`
`dotnet run --project src/Valet/Valet.csproj -- version`
Note - this functionality works for all commands _except_ update, since there would be no reason to suggest an update if they are currently updating
Closes #53
=> Check if valet container is current

src/Valet/App.cs, src/Valet/Constants.cs
This change will store and read environment variables defined in a `.env.local` file that can be used to authenticate with GHCR to fetch new versions of the valet-cli container.  This also updates the `configure` command to interactively set these credentials.
> Configure these credentials
```bash{:copy}
dotnet run --project src/Valet/Valet.csproj -- configure
```
> Use these credentials
```bash{:copy}
dotnet run --project src/Valet/Valet.csproj -- update
```
=> Configure GHCR credentials in configure command

src/Valet.UnitTests/Models/VariableTests.cs, src/Valet/Models/Variable.cs
This masks the `GHCR_PASSWORD` value in the terminal prompt when running the `configure` command
> Configure these credentials
```bash{:copy}
dotnet run --project src/Valet/Valet.csproj -- configure
```
> Use these credentials
```bash{:copy}
dotnet run --project src/Valet/Valet.csproj -- update
```
=> Mask ghcr password in prompt

CONTRIBUTING.md
Updates the redirected link as per the shut down of`help.`: https://github.blog/changelog/2022-08-22-help-github-com-will-soon-take-you-to-github-support/
Click the link.
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
=> Avoid dead links in CONTRIBUTING.md

src/Valet/Commands/Circle/Audit.cs
This is adding a `--include-from` option for CircleCI audits for users to control exactly which repositories to include in an audit. This is to help scenarios where customers have a large GitHub org (>5k repos) where only a portion are configured with CircleCI. By using this option, customers can mitigate any potential API limit concerns with running an audit.
> repositories.txt
```txt
circle-yaml-aliases-example
circle-ci-ruby-example
```
```bash
$ dotnet run --project src/Valet/Valet.csproj -- audit circle-ci -o tmp --include-from repositories.txt --circle-ci-organization valet-testing-unit
```
cc/ github/valet#4539
=> Allow for user input to control which repositories to include in a cci audit

src/Valet/Commands/Common.cs, src/Valet/Commands/Migrate.cs
- Exposes new `migrate` options for `--commit-message` and `--workflow-file-prefix`
- Moves `--github-access-token` and `--github-instance-url` to global options so they are exposed on the `dry-run`, `audit`, and `migrate` commands
1. Publish changes
```
dotnet publish src/Valet/Valet.csproj -c Release -r osx-x64 --self-contained -o dist/osx-x64 --no-restore -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true 
```
2. Update Valet
```
dist/osx-x64/gh-valet update
```
3. Run `migrate`, `dry-run` and `audit` commands
```
dist/osx-x64/gh-valet COMMAND HERE
```
👀 
Closes #76
=> Update CLI with new `migrate` options 

src/Valet/Constants.cs
This relays the `INSTALLATION_TYPE` environment variable to the valet-cli container when running from `gh valet ...`
Needs github/valet#4615
Needs github/valet.services#27
=> Expose host INSTALLATION_TYPE env var to container

src/Valet/Commands/Circle/Common.cs, src/Valet/Commands/Jenkins/Common.cs, src/Valet/Commands/Travis/Common.cs, src/Valet/Constants.cs
This updates the `configure` prompt to remove the `*_SOURCE_GITHUB_(ACCESS_TOKEN|INSTANCE_URL)` options as they are not needed for the vast majority of use cases. They can still be provided as environment variables or cli options, but we now default to reusing the values for `GITHUB_ACCESS_TOKEN` and `GITHUB_INSTANCE_URL` instead.
```console
$ dotnet run --project src/Valet/Valet.csproj -- configure
A new version of the Valet CLI is available. Run 'gh valet update' to update.
✔ Which CI providers are you configuring?: Jenkins
Enter the following values (leave empty to omit):
✔ GitHub handle used to authenticate with the GitHub Container Registry: 
✔ Personal access token to authenticate with the GitHub Container Registry: 
✔ Personal access token for GitHub: 
✔ Base url of the GitHub …
```
=> Remove legacy prompts

src/Valet/Services/ProcessService.cs
This reverts commit 5fc0e49cfe34342f33154675cec73799520a0746.
The commit above was causing output to not print to the console until the process was finished.
```
dotnet run --project src/Valet/Valet.csproj -- audit azure-devops -o tmp
```
=> Fix console output hanging while Valet processes

README.md, src/Valet/Commands/Forecast.cs, src/Valet/Commands/GitHub/Forecast.cs
Adding the GitHub forecast subcommand to gh valet.
`dotnet run --project src/Valet/Valet.csproj -- forecast github --organization valet-dev-testing -o tmp`
`dotnet run --project src/Valet/Valet.csproj -- forecast github -o valet-testing-unit -o tmp`
`dotnet run --project src/Valet/Valet.csproj -- forecast github --organization github -r valet -o tmp` (if you have SSO enabled for your github token)
Closes #85
=> GitHub forecast subcommand

src/Valet.UnitTests/Services/DockerServiceTests.cs, src/Valet/Services/DockerService.cs
Adds 1 additional check for docker authentication error messages to apply user-friendly formatting
On a new, clean installation w/o valid docker credentials cached or providing valid credentials as input, run the `gh valet update` call and verify that the user is presented with the friendly error message rather than the `Error response from daemon` error that Docker returns
=> Additional docker auth error mesage 

src/Valet/Commands/AzureDevOps/Audit.cs, src/Valet/Commands/AzureDevOps/BuildPipeline/DryRun.cs, src/Valet/Commands/AzureDevOps/BuildPipeline/Migrate.cs, src/Valet/Commands/AzureDevOps/Common.cs, src/Valet/Commands/AzureDevOps/DryRun.cs, src/Valet/Commands/AzureDevOps/Migrate.cs, src/Valet/Commands/AzureDevOps/ReleasePipeline/DryRun.cs, src/Valet/Commands/AzureDevOps/ReleasePipeline/Migrate.cs, src/Valet/Valet.csproj
Make sure you have the latest version of the Valet container: 
`gh valet update`
Build c# project:
`dotnet build /Users/bguereca/1ESLighthouse/gh-valet/gh-valet/src/Valet/Valet.csproj `
Make sure you add a sample ADO pipeline to `output/pipeline.yml`
```
trigger:
- main
pool:
vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
displayName: 'Run a one-line script'
- script: |
echo Add other tasks to build, test, and deploy your project.
echo See https://aka.ms/yaml
displayName: 'Run a multi-line script'
```
also `output/config.yaml`:
```
pipelines:
- project_slug: valet-testing/unit/basic-pipeline-sample
source_file_path: output/pipeline.yml
- project_slug: valet-testing/unit/directed-acrylic-graph-pipeline
source_file_path: output/pipeline.yml
```
Regular commands: 
`dotnet run …
=> Updating options on GH-Valet with new ADO options 

src/Valet/Commands/AzureDevOps/Audit.cs, src/Valet/Commands/AzureDevOps/BuildPipeline/DryRun.cs, src/Valet/Commands/AzureDevOps/BuildPipeline/Migrate.cs, src/Valet/Commands/AzureDevOps/Common.cs, src/Valet/Commands/AzureDevOps/ReleasePipeline/DryRun.cs, src/Valet/Commands/Circle/Audit.cs, src/Valet/Commands/Circle/Common.cs, src/Valet/Commands/Circle/DryRun.cs, src/Valet/Commands/Circle/Migrate.cs, src/Valet/Commands/GitLab/Audit.cs, src/Valet/Commands/GitLab/Common.cs, src/Valet/Commands/GitLab/DryRun.cs, src/Valet/Commands/GitLab/Migrate.cs, src/Valet/Commands/Jenkins/Audit.cs, src/Valet/Commands/Jenkins/Common.cs, src/Valet/Commands/Jenkins/DryRun.cs, src/Valet/Commands/Jenkins/Migrate.cs, src/Valet/Commands/Travis/Audit.cs, src/Valet/Commands/Travis/Common.cs, src/Valet/Commands/Travis/DryRun.cs, src/Valet/Commands/Travis/Migrate.cs
Adding `--config-file-path` option to all providers. 
Make sure you have the latest version of the Valet container: 
`gh valet update`
Build c# project:
`dotnet build /Users/bguereca/1ESLighthouse/gh-valet/gh-valet/src/Valet/Valet.csproj `
.
.
.
.
.
<details>
<summary>Azure DevOps commands</summary>
`output/ado/pipeline.yml`
```
trigger:
- main
pool:
vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
displayName: 'Run a one-line script'
- script: |
echo Add other tasks to build, test, and deploy your project.
echo See https://aka.ms/yaml
displayName: 'Run a multi-line script'
```
also `output/ado/config.yaml`:
```
source_files:
- repository_slug: valet-testing/build-playground
path: output/ado/pipeline.yml
- repository_slug: valet-testing/unit/directed-acrylic-graph-pipeline
path: …
```
=> Added `--config-file-path` option to all migrate and dry run commands 

.github/workflows/ci.yml
Adds required permissions for publishing unit test results. 
Docs: https://github.com/EnricoMi/publish-unit-test-result-action#permissions
- Green CI checks. 
- There is a comment with the unit test results.
=> CI: add required permissions for publishing unit test results.
